FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["gunicorn","-k","uvicorn.workers.UvicornWorker","-b","0.0.0.0:8080","app:app"]