TASK_CREATED = "TASK_CREATED"
TASK_UPDATED = "TASK_UPDATED"
TASK_DELETED = "TASK_DELETED"
TASK_COMPLETED = "TASK_COMPLETED"

REMINDER_CREATED = "REMINDER_CREATED"
REMINDER_UPDATED = "REMINDER_UPDATED"
REMINDER_DELETED = "REMINDER_DELETED"
REMINDER_COMPLETED = "REMINDER_COMPLETED"

ENERGY_CHANGED = "ENERGY_CHANGED"

STREAK_UPDATED = "STREAK_UPDATED"

SPRINT_GENERATED = "SPRINT_GENERATED"

LOGIN = "LOGIN"
LOGOUT = "LOGOUT"